# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Important commands:
#
# install the pre-commit & pre-push hooks:
# $ pre-commit install --hook-type pre-commit --hook-type pre-push
#
# uninstall the pre-commit & pre-push hooks:
# $ pre-commit uninstall --hook-type pre-commit --hook-type pre-push
#
# run the hooks on all the files:
# $ pre-commit run --all-files
#
# run the hooks on the staged files:
# $ pre-commit run --staged
#
# Unit tests are executed for the push hook and the coverage is checked.
#

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: check-merge-conflict
#  - id: check-json
#  - id: check-yaml
#    args: [--unsafe]  # just check syntax
  - id: check-toml
  - id: trailing-whitespace
  - id: mixed-line-ending

- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: "1.1.0"
  hooks:
    - id: tox-ini-fmt

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]

  - id: black
    name: black
    entry: black
    language: system
    types: [python]

  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]


- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
  - id: pycln

#- repo: https://github.com/PyCQA/pydocstyle
#  rev: 6.3.0
#  hooks:
#  - id: pydocstyle

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml", "-r", "src"]
    additional_dependencies: ["bandit[toml]"]

- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pytest --doctest-modules tests/unit
    pass_filenames: false
    always_run: true
    language: system
    stages: [push]
